<?php

function MarkList_menu()
{
  $items = array();
  $items['add_student'] = array(
    'title' =>'Add Student',
    'description'=>'Add new details to database',
    'page callback'=>'drupal_get_form',
    'page arguments'=>array('field_for_students'),
    'access callback'=>'access_callback_function',
  );
  $items['class_adding']=array(
    'page callback'=>'class_name',
    'access callback'=>'user_access',
    'access arguments'=>array('access content'),
    'type'=>MENU_CALLBACK
  );
  $items['student_adding']=array(
    'page callback'=>'student',
    'access callback'=>'user_access',
    'access arguments'=>array('access content'),
    'type'=>MENU_CALLBACK
  );
  $items['add_class'] = array(
    'title' =>'Add Class',
    'description'=>'Add new details of classes to database',
    'page callback'=>'drupal_get_form',
    'page arguments'=>array('field_for_class'),
    'access callback'=>'access_callback_function',
  );
  $items['add_marks'] = array(
    'title' =>'Add Marks',
    'description'=>'Add marks of students to database',
    'page callback'=>'drupal_get_form',
    'page arguments'=>array('field_for_marks'),
    'access callback'=>'access_callback_function',
  );
  return $items;
}

function access_callback_function()
{
  return !user_is_anonymous();
}

function field_for_students()
{
  $form = array();
  $form['name']=array(
    '#type' => 'textfield',
    '#title' => 'Student Name'
  );
  $result = db_select('class','u')
  ->fields('u', array('id','name','division'))
  ->execute()
  ->fetchAll();
  foreach ($result as $r) {
    $opt[$r->id] = $r->name.' - '.$r->division;
  }
  $form['class']=array(
    '#type' => 'select',
    '#title' => 'Class',
    '#options' => $opt
  );
  $form['#suffix']='<input type="button" id="studentData" value="Submit" class="form-submit">';

  drupal_add_js(drupal_get_path('module','MarkList'). "/base.js");
  global $user;
  $newToken = drupal_get_token("marker".$user->uid);
  drupal_add_js('var mytoken="'.$newToken.'";', 'inline');
  return $form;
}

function field_for_class()
{
  $form = array();
  $form['name']=array(
    '#type' => 'textfield',
    '#title' => 'Class',
    '#maxlength' => 10
  );
  $form['division']=array(
    '#type' => 'textfield',
    '#title' => 'Division',
    '#maxlength' => 1
  );
  $form['#suffix']='<input type="button" id="classData" value="Submit" class="form-submit">';

  drupal_add_js(drupal_get_path('module','MarkList'). "/base.js");
  global $user;
  $newToken = drupal_get_token("marker".$user->uid);
  drupal_add_js('var mytoken="'.$newToken.'";', 'inline');
  return $form;
}

function field_for_marks()
{
  if(isset($_GET['id'])){
    $result = db_select('class','u')
    ->fields('u', array('id','name','division'))
    ->condition('id',$_GET['id'],'=')
    ->execute()
    ->fetchAssoc();
    if(isset($_GET['sid'])){
      $students = db_select('student','u')
      ->fields('u', array('id','name'))
      ->condition('class_id',$_GET['id'],'=')
      ->condition('id',$_GET['sid'],'=')
      ->execute()
      ->fetchAssoc();
      $form = array();
      $form['mark'] = array(
        '#type' => 'textfield',
        '#title' => 'Mark'
      );
      $form['#suffix']='<input type="button" id="studentMark" value="Submit" class="form-submit">
      <h4>Name : '.$students['name'].'</h4><h4>Class : '.$result['name'].' - '.$result['division'].'</h4>';
      drupal_add_js(drupal_get_path('module','MarkList'). "/base.js");
      global $user;
      $newToken = drupal_get_token("marker".$user->uid);
      drupal_add_js('var mytoken="'.$newToken.'";', 'inline');
      return $form;
    }else{
      if($result){
        $form = array();
        $students = db_select('student','u')
        ->fields('u', array('id','name'))
        ->condition('class_id',$_GET['id'],'=')
        ->execute()
        ->fetchAll();
        $out = '<h3>Class : '.$result['name'].' - '.$result['division'].'</h3>';
        foreach ($students as $s) {
          $out .= '<a href="add_marks?id='.$_GET['id'].'&sid='.$s->id.'"><li>'.$s->name.'</li></a>';
        }
        $form['#suffix']= $out;
        return $form;
      }else{
        $form['#suffix']= 'Invalid Class ID!';
        return $form;
      }
    }
  }else{
    $result = db_select('class','u')
    ->fields('u', array('id','name','division'))
    ->execute()
    ->fetchAll();
    $out='';
    foreach ($result as $r) {
      $out .= '<a href="add_marks?id='.$r->id.'"><h3><li>'.$r->name.' - '.$r->division.'</li></h3></a>';
    }
    $form['#suffix']=$out;
    return $form;
  }
}

function class_name(){
  global $user;
  if (empty($_GET['token']) || !drupal_valid_token($_GET['token'], 'marker'.$user->uid)) {
    return MENU_ACCESS_DENIED;
  }else{
    $id = db_insert('class')
    ->fields(array(
      'name'=>filter_xss(ucfirst($_GET['class_name'])),
      'division'=>filter_xss(ucfirst($_GET['division_name']))
    ))
    ->execute();
    echo filter_xss(ucfirst($_GET['class_name']))." added successfully";
  }
}

  function student(){
    global $user;
    if (empty($_GET['token']) || !drupal_valid_token($_GET['token'], 'marker'.$user->uid)) {
      return MENU_ACCESS_DENIED;
    }else{
      $id = db_insert('student')
      ->fields(array(
        'name'=>filter_xss(ucwords($_GET['name'])),
        'class_id'=>$_GET['class_id']
      ))
      ->execute();
      echo filter_xss(ucfirst($_GET['name']))." added successfully";
    }
  }

 ?>
