<?php

function MarkList_menu()
{
  $items = array();
  $items['add_students'] = array(
    'title' =>'Add Student',
    'description'=>'Add new details to database',
    'page callback'=>'drupal_get_form',
    'page arguments'=>array('field_for_students'),
    'access callback'=>'access_callback_function',
  );
  $items['class_adding']=array(
    'page callback'=>'add_class',
    'access callback'=>'user_access',
    'access arguments'=>array('access content'),
    'type'=>MENU_CALLBACK
  );
  $items['add_class'] = array(
    'title' =>'Add Class',
    'description'=>'Add new details of classes to database',
    'page callback'=>'drupal_get_form',
    'page arguments'=>array('field_for_class'),
    'access callback'=>'access_callback_function',
  );
  return $items;
}

function access_callback_function()
{
  return !user_is_anonymous();
}

function field_for_students()
{
  $form = array();
  $form['name']=array(
    '#type' => 'textfield',
    '#title' => 'Student Name'
  );
  $result = db_select('class','u')
  ->fields('u', array('id','name','division'))
  ->execute()
  ->fetchAll();
  $form['class']=array(
    '#type' => 'select',
    '#title' => 'Class',
    '#options' => $result
  );
  $form['#suffix']='<input type="button" id="studentData" value="Submit" class="form-submit">';

  drupal_add_js(drupal_get_path('module','MarkList'). "/base.js");
  global $user;
  $newToken = drupal_get_token("marker".$user->uid);
  drupal_add_js('var mytoken="'.$newToken.'";', 'inline');
  return $form;
}

function field_for_class()
{
  $form = array();
  $form['name']=array(
    '#type' => 'textfield',
    '#title' => 'Class',
    '#maxlength' => 10
  );
  $form['division']=array(
    '#type' => 'textfield',
    '#title' => 'Division',
    '#maxlength' => 1
  );
  $form['#suffix']='<input type="button" id="classData" value="Submit" class="form-submit">';

  drupal_add_js(drupal_get_path('module','MarkList'). "/base.js");
  global $user;
  $newToken = drupal_get_token("marker".$user->uid);
  drupal_add_js('var mytoken="'.$newToken.'";', 'inline');
  return $form;
}

function add_class(){
  global $user;
  if (empty($_GET['token']) || !drupal_valid_token($_GET['token'], 'marker'.$user->uid)) {
    return MENU_ACCESS_DENIED;
  }else{
    $id = db_insert('class')
    ->fields(array(
      'name'=>filter_xss(ucfirst($_GET['class_name'])),
      'division'=>filter_xss(ucfirst($_GET['division_name']))
    ))
    ->execute();
    echo filter_xss(ucfirst($_GET['class_name']))." added successfully";
  }
}
 ?>
