<?php

function MarkList_menu()
{
  $items = array();
  $items['add_student'] = array(
    'title' =>'Add Student',
    'description'=>'Add new details to database',
    'page callback'=>'drupal_get_form',
    'page arguments'=>array('field_for_students'),
    'access callback'=>'access_callback_function',
  );
  $items['class_adding']=array(
    'page callback'=>'class_name',
    'access callback'=>'user_access',
    'access arguments'=>array('access content'),
    'type'=>MENU_CALLBACK
  );
  $items['student_adding']=array(
    'page callback'=>'student',
    'access callback'=>'user_access',
    'access arguments'=>array('access content'),
    'type'=>MENU_CALLBACK
  );
  $items['add_class'] = array(
    'title' =>'Add Class',
    'description'=>'Add new details of classes to database',
    'page callback'=>'drupal_get_form',
    'page arguments'=>array('field_for_class'),
    'access callback'=>'access_callback_function',
  );
  $items['add_marks'] = array(
    'title' =>'Add Marks',
    'description'=>'Add marks of students to database',
    'page callback'=>'drupal_get_form',
    'page arguments'=>array('field_for_marks'),
    'access callback'=>'access_callback_function',
  );
  $items['student_mark']=array(
    'page callback'=>'mark',
    'access callback'=>'user_access',
    'access arguments'=>array('access content'),
    'type'=>MENU_CALLBACK
  );
  $items['mark_list']=array(
    'title'=>'Students Mark List',
    'description'=>'Display all students mark by classes',
    'page callback'=>'mark_list',
    'access callback'=>'user_access',
    'access arguments'=>array('access content'),
    'type'=>MENU_NORMAL_ITEM
  );
  return $items;
}

function access_callback_function()
{
  return !user_is_anonymous();
}

function field_for_students()
{
  $result = db_select('class','u')
  ->fields('u', array('id','name','division'))
  ->execute()
  ->fetchAll();
  if($result){
    $form = array();
    $form['name']=array(
      '#type' => 'textfield',
      '#title' => 'Student Name'
    );
    foreach ($result as $r) {
      $opt[$r->id] = $r->name.' - '.$r->division;
    }
    $form['class']=array(
      '#type' => 'select',
      '#title' => 'Class',
      '#options' => $opt
    );
    $form['#suffix']='<input type="button" id="studentData" value="Submit" class="form-submit">';

    drupal_add_js(drupal_get_path('module','MarkList'). "/base.js");
    global $user;
    $newToken = drupal_get_token("marker".$user->uid);
    drupal_add_js('var mytoken="'.$newToken.'";', 'inline');
    return $form;
  }else{
    $form['#suffix']='There no class, <a href="add_class">click here</a> to add class';
    return $form;
  }
}

function field_for_class()
{
  $form = array();
  $form['name']=array(
    '#type' => 'textfield',
    '#title' => 'Class',
    '#maxlength' => 10
  );
  $form['division']=array(
    '#type' => 'textfield',
    '#title' => 'Division',
    '#maxlength' => 1
  );
  $form['#suffix']='<input type="button" id="classData" value="Submit" class="form-submit">';

  drupal_add_js(drupal_get_path('module','MarkList'). "/base.js");
  global $user;
  $newToken = drupal_get_token("marker".$user->uid);
  drupal_add_js('var mytoken="'.$newToken.'";', 'inline');
  return $form;
}

function field_for_marks()
{
  if(isset($_GET['id'])){
    $result = db_select('class','u')
    ->fields('u', array('id','name','division'))
    ->condition('id',$_GET['id'],'=')
    ->execute()
    ->fetchAssoc();
    if(isset($_GET['sid'])){
      $students = db_select('student','u')
      ->fields('u', array('id','name'))
      ->condition('class_id',$_GET['id'],'=')
      ->condition('id',$_GET['sid'],'=')
      ->execute()
      ->fetchAssoc();
      $form = array();
      $form['mark'] = array(
        '#type' => 'textfield',
        '#title' => 'Mark'
      );
      $form['#suffix']='<input type="button" id="studentMark" value="Submit" class="form-submit">
      <h4>Name : '.$students['name'].'</h4><h4>Class : '.$result['name'].' - '.$result['division'].'</h4><a href="add_marks?id='.$_GET['id'].'">Back to class</a>';
      drupal_add_js(drupal_get_path('module','MarkList'). "/base.js");
      global $user;
      $newToken = drupal_get_token("marker".$user->uid);
      drupal_add_js('var mytoken="'.$newToken.'";', 'inline');
      return $form;
    }else{
      if($result){
        $form = array();
        $students = db_select('student','u')
        ->fields('u', array('id','name'))
        ->condition('class_id',$_GET['id'],'=')
        ->execute()
        ->fetchAll();
        if($students){
          $out = '<h3>Class : '.$result['name'].' - '.$result['division'].'</h3>';
          foreach ($students as $s) {
            $out .= '<a href="add_marks?id='.$_GET['id'].'&sid='.$s->id.'"><li>'.$s->name.'</li></a>';
          }
        }else {
          $out = 'There is no students in the class ('.$result['name'].' - '.$result['division'].'), <a href="add_student">click here</a> to add students';
        }
        $form['#suffix']= $out;
        return $form;
      }else{
        $form['#suffix']= 'Invalid Class ID!';
        return $form;
      }
    }
  }else{
    $result = db_select('class','u')
    ->fields('u', array('id','name','division'))
    ->execute()
    ->fetchAll();
    if($result){
    $out='';
    foreach ($result as $r) {
      $out .= '<a href="add_marks?id='.$r->id.'"><h3><li>'.$r->name.' - '.$r->division.'</li></h3></a>';
    }
    $form['#suffix']=$out;
    return $form;
  }else {
    $form['#suffix']='There no class, <a href="add_class">click here</a> to add class';
    return $form;
  }
  }
}

function class_name(){
  global $user;
  if (empty($_GET['token']) || !drupal_valid_token($_GET['token'], 'marker'.$user->uid)) {
    return MENU_ACCESS_DENIED;
  }else{
    $id = db_insert('class')
    ->fields(array(
      'name'=>filter_xss(ucfirst($_GET['class_name'])),
      'division'=>filter_xss(ucfirst($_GET['division_name']))
    ))
    ->execute();
    echo filter_xss(ucfirst($_GET['class_name']))." added successfully";
  }
}

  function student(){
    global $user;
    if (empty($_GET['token']) || !drupal_valid_token($_GET['token'], 'marker'.$user->uid)) {
      return MENU_ACCESS_DENIED;
    }else{
      $id = db_insert('student')
      ->fields(array(
        'name'=>filter_xss(ucwords($_GET['name'])),
        'class_id'=>$_GET['class_id']
      ))
      ->execute();
      echo filter_xss(ucfirst($_GET['name']))." added successfully";
    }
  }

  function mark(){
    global $user;
    if (empty($_GET['token']) || !drupal_valid_token($_GET['token'], 'marker'.$user->uid)) {
      return MENU_ACCESS_DENIED;
    }else{
      $student = db_select('student','u')
      ->fields('u', array('id','name'))
      ->condition('class_id',$_GET['class_id'],'=')
      ->condition('id',$_GET['student_id'],'=')
      ->execute()
      ->fetchAssoc();
      if($student){
        $check = db_select('marks','u')
        ->fields('u', array('id'))
        ->condition('class_id',$_GET['class_id'],'=')
        ->condition('student_id',$_GET['student_id'],'=')
        ->execute()
        ->fetchAssoc();
        if($check){
          $update = db_update('marks')
          ->fields(array(
            'mark' =>filter_xss($_GET['mark'])
          ))
          ->condition('class_id',$_GET['class_id'],'=')
          ->condition('student_id',$_GET['student_id'],'=')
          ->execute();
          echo $student['name']."'s mark updated successfully";
        }else{
          $id = db_insert('marks')
          ->fields(array(
            'mark'=>filter_xss($_GET['mark']),
            'class_id'=>$_GET['class_id'],
            'student_id'=>$_GET['student_id']
          ))
          ->execute();
          echo $student['name']."'s mark added successfully";
        }
      }else{
        return MENU_ACCESS_DENIED;
      }
    }
  }

  function mark_list()
  {
    if (isset($_GET['id'])) {
      $check = db_select('class','u')
      ->fields('u', array('id','name','division'))
      ->condition('id',$_GET['id'],'=')
      ->execute()
      ->fetchAssoc();
      if($check){
        $marks = db_select('marks','u')
          ->fields('u', array('mark','student_id'))
          ->condition('class_id',$_GET['id'],'=')
          ->execute()
          ->fetchAll();
        if($marks){
          $out = '<table><th><td>Name</td><td>Mark</td></th>';
          $count = 1;
          foreach ($marks as $m) {
            $student = db_select('student','u')
              ->fields('u', array('name'))
              ->condition('id',$m->student_id,'=')
              ->execute()
              ->fetchAssoc();
            $out .= '<tr><td>'.$count.'</td><td>'.$student['name'].'</td><td>'.$m->mark.'</td></tr>';
            $count++;
          }
          $out .= '</table>';
          return $out;
        }else {
          return 'Students mark is not added';
        }
      }else{
        return 'Invalid class ID';
      }
    }else {
      $result = db_select('class','u')
      ->fields('u', array('id','name','division'))
      ->execute()
      ->fetchAll();
      $out = '';
      if($result){
        foreach ($result as $r) {
          $out .= '<a href="mark_list?id='.$r->id.'"><h2><li>'.$r->name.' - '.$r->division.'</li></h2></a>';
        }
      }else {
        $out = 'Something went wrong, please contact the admin!';
      }
      return $out;
    }
  }
 ?>
